version: '3.8'

services:
  conversao-temperatura:
    container_name: conversao-temperatura
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080

    